version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.itemConfig:
        ItemConfig:
          staticFields:
            VARIABLE_PREFIX:
              name: VARIABLE_PREFIX
              modifiers:
              - public
              - static
              - final
              type:
                basic: String
                full: java.lang.String
                nullable: true
            error_bucket:
              name: error_bucket
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
                nullable: true
            error_item_config:
              name: error_item_config
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
                nullable: true
            error_line:
              name: error_line
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
                nullable: true
            error_root:
              name: error_root
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
                nullable: true
          constructors:
          - modifiers:
            - public
          methods:
          - name: BuildBuckets
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: ConfigureEntityOnCreate
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: GameEntity
                full: zombie.entity.GameEntity
            return:
              type:
                basic: void
                full: void
          - name: ConfigureEntitySpawned
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: GameEntity
                full: zombie.entity.GameEntity
            - name: arg1
              type:
                basic: ItemPickInfo
                full: zombie.inventory.ItemPickInfo
            return:
              type:
                basic: void
                full: void
          - name: Load
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: OnScriptsLoaded
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ScriptLoadMode
                full: zombie.scripting.ScriptLoadMode
            return:
              type:
                basic: void
                full: void
          - name: PreReload
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          javaType: class
          extends: BaseScriptObject
