version: '1.1'
languages:
  java:
    packages:
      java.lang:
        Package:
          extends: java.lang.NamedPackage
          modifiers:
          - public
          notes: "Represents metadata about a run-time package associated with a class\
            \ loader.\n Metadata includes annotations, versioning, and sealing.\n\
            \ \n Annotations for the run-time package are read from package-info.class\n\
            \ at the same code source as classes in the run-time package.\n \n The\
            \ set of classes that make up the run-time package may implement a\n particular\
            \ specification. The specification title, version, and vendor\n (indicating\
            \ the owner/maintainer of the specification) can be provided\n when the\
            \ Package is defined. An application can ask if the\n Package is compatible\
            \ with a particular specification version\n by using the Package.isCompatibleWith(String)\n\
            \ method. In addition, information about the actual classes that make\
            \ up the\n run-time package can be provided when the Package is defined.\n\
            \ This information consists of an implementation title, version, and vendor\n\
            \ (indicating the supplier of the classes).\n \n A Package may be explicitly\
            \ defined with\n the ClassLoader.definePackage(String, String, String,\
            \ String, String, String, String, URL) method.\n The caller supplies the\
            \ specification and implementation titles, versions, and\n vendors. The\
            \ caller also indicates whether the package is\n sealed.\n If a Package\
            \ is not explicitly defined for a run-time package when\n a class in that\
            \ run-time package is defined, then a Package is\n automatically defined\
            \ by the class's defining class loader, as follows.\n \n A Package automatically\
            \ defined for classes in a named module has\n the following properties:\n\
            \ \n The name of the package is derived from the binary names\n     of\
            \ the classes. Since classes in a named module must be in a named package,\n\
            \     the derived name is never empty.\n The package is sealed with the\
            \ module location as the code source, if known.\n The specification and\
            \ implementation titles, versions, and vendors\n     are unspecified.\n\
            \ Any annotations on the package are read from package-info.class\n  \
            \   as specified above.\n \n \n A Package automatically defined for classes\
            \ in an unnamed module\n has the following properties:\n \n The name of\
            \ the package is either \"\" (for classes in an unnamed package)\n   \
            \  or derived from the binary names of the classes\n     (for classes\
            \ in a named package).\n The package is not sealed.\n The specification\
            \ and implementation titles, versions, and vendors\n     are unspecified.\n\
            \ Any annotations on the package are read from package-info.class\n  \
            \   as specified above.\n \n\n \n A Package can be obtained with the Package.getPackage(String)\
            \ and ClassLoader.getDefinedPackage(String) methods.\n Every Package defined\
            \ by a class loader can be obtained\n with the Package.getPackages() and\n\
            \ ClassLoader.getDefinedPackages() methods."
          fields:
            packageInfo:
              name: packageInfo
              modifiers:
              - private
              type:
                basic: Class
                full: java.lang.Class<?>
            versionInfo:
              name: versionInfo
              modifiers:
              - private
              type:
                basic: Package.VersionInfo
                full: java.lang.Package$VersionInfo
          constructors:
          - modifiers:
            - package
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            - name: arg2
              type:
                basic: String
                full: java.lang.String
            - name: arg3
              type:
                basic: String
                full: java.lang.String
            - name: arg4
              type:
                basic: String
                full: java.lang.String
            - name: arg5
              type:
                basic: String
                full: java.lang.String
            - name: arg6
              type:
                basic: String
                full: java.lang.String
            - name: arg7
              type:
                basic: URL
                full: java.net.URL
            - name: arg8
              type:
                basic: ClassLoader
                full: java.lang.ClassLoader
          - modifiers:
            - package
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: Module
                full: java.lang.Module
          methods:
          - name: getAnnotation
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class
                full: java.lang.Class<A>
            return:
              type:
                basic: A
                full: A
          - name: getAnnotations
            modifiers:
            - public
            return:
              type:
                basic: Annotation
                full: java.lang.annotation.Annotation[]
          - name: getAnnotationsByType
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class
                full: java.lang.Class<A>
            return:
              type:
                basic: A
                full: A[]
          - name: getDeclaredAnnotation
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class
                full: java.lang.Class<A>
            return:
              type:
                basic: A
                full: A
          - name: getDeclaredAnnotations
            modifiers:
            - public
            return:
              type:
                basic: Annotation
                full: java.lang.annotation.Annotation[]
          - name: getDeclaredAnnotationsByType
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class
                full: java.lang.Class<A>
            return:
              type:
                basic: A
                full: A[]
          - name: getImplementationTitle
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getImplementationVendor
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getImplementationVersion
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getPackageInfo
            modifiers:
            - private
            return:
              type:
                basic: Class
                full: java.lang.Class<?>
          - name: getSpecificationTitle
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getSpecificationVendor
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getSpecificationVersion
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: hashCode
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: isAnnotationPresent
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class
                full: java.lang.Class<? extends java.lang.annotation.Annotation>
            return:
              type:
                basic: boolean
                full: boolean
          - name: isCompatibleWith
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: isSealed
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isSealed
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: URL
                full: java.net.URL
            return:
              type:
                basic: boolean
                full: boolean
          - name: toString
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          staticMethods:
          - name: getPackage
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: Package
                full: java.lang.Package
          - name: getPackages
            modifiers:
            - public
            - static
            return:
              type:
                basic: Package
                full: java.lang.Package[]
          - name: lambda$getPackages$0
            modifiers:
            - private
            - static
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: Package
                full: java.lang.Package[]
