version: '1.1'
languages:
  java:
    packages:
      zombie.core:
        PerformanceSettings:
          modifiers:
          - public
          - final
          staticFields:
            AnimationSkip:
              name: AnimationSkip
              modifiers:
              - public
              - static
              type:
                basic: int
            BaseStaticAnimFramerate:
              name: BaseStaticAnimFramerate
              modifiers:
              - public
              - static
              type:
                basic: int
            FogQuality:
              name: FogQuality
              modifiers:
              - public
              - static
              type:
                basic: int
            InterpolateAnims:
              name: InterpolateAnims
              modifiers:
              - public
              - static
              type:
                basic: boolean
            LightingFPS:
              name: LightingFPS
              modifiers:
              - public
              - static
              type:
                basic: int
            LightingFrameSkip:
              name: LightingFrameSkip
              modifiers:
              - public
              - static
              type:
                basic: int
            LightingThread:
              name: LightingThread
              modifiers:
              - public
              - static
              type:
                basic: boolean
            ManualFrameSkips:
              name: ManualFrameSkips
              modifiers:
              - public
              - static
              type:
                basic: int
            ModelLighting:
              name: ModelLighting
              modifiers:
              - public
              - static
              type:
                basic: boolean
            NewRoofHiding:
              name: NewRoofHiding
              modifiers:
              - public
              - static
              type:
                basic: boolean
            PuddlesQuality:
              name: PuddlesQuality
              modifiers:
              - public
              - static
              type:
                basic: int
            UseFBOs:
              name: UseFBOs
              modifiers:
              - public
              - static
              type:
                basic: boolean
            WaterQuality:
              name: WaterQuality
              modifiers:
              - public
              - static
              type:
                basic: int
            ZombieAnimationSpeedFalloffCount:
              name: ZombieAnimationSpeedFalloffCount
              modifiers:
              - public
              - static
              type:
                basic: int
            ZombieBonusFullspeedFalloff:
              name: ZombieBonusFullspeedFalloff
              modifiers:
              - public
              - static
              type:
                basic: int
            auto3DZombies:
              name: auto3DZombies
              modifiers:
              - public
              - static
              type:
                basic: boolean
            instance:
              name: instance
              modifiers:
              - public
              - static
              - final
              type:
                basic: PerformanceSettings
            numberZombiesBlended:
              name: numberZombiesBlended
              modifiers:
              - public
              - static
              type:
                basic: int
          constructors:
          - modifiers:
            - public
          methods:
          - name: getFogQuality
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getFramerate
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getLightingFPS
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getLightingQuality
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getNewRoofHiding
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: getPuddlesQuality
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getUIRenderFPS
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getWaterQuality
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: isFramerateUncapped
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: setFogQuality
            modifiers:
            - public
            parameters:
            - name: fogQuality
              type:
                basic: int
            return:
              type:
                basic: void
          - name: setFramerate
            modifiers:
            - public
            parameters:
            - name: framerate
              type:
                basic: int
            return:
              type:
                basic: void
          - name: setFramerateUncapped
            modifiers:
            - public
            parameters:
            - name: val
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setLightingFPS
            modifiers:
            - public
            parameters:
            - name: fps
              type:
                basic: int
            return:
              type:
                basic: void
          - name: setLightingQuality
            modifiers:
            - public
            parameters:
            - name: lighting
              type:
                basic: int
            return:
              type:
                basic: void
          - name: setNewRoofHiding
            modifiers:
            - public
            parameters:
            - name: enabled
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setPuddlesQuality
            modifiers:
            - public
            parameters:
            - name: puddles
              type:
                basic: int
            return:
              type:
                basic: void
          - name: setWaterQuality
            modifiers:
            - public
            parameters:
            - name: water
              type:
                basic: int
            return:
              type:
                basic: void
          staticMethods:
          - name: getLockFPS
            modifiers:
            - public
            - static
            return:
              type:
                basic: int
          - name: isUncappedFPS
            modifiers:
            - public
            - static
            return:
              type:
                basic: boolean
          - name: setLockFPS
            modifiers:
            - public
            - static
            parameters:
            - name: lockFPS
              type:
                basic: int
            return:
              type:
                basic: void
          - name: setUncappedFPS
            modifiers:
            - public
            - static
            parameters:
            - name: uncappedFPS
              type:
                basic: boolean
            return:
              type:
                basic: void
          javaType: class
          extends: Object
