version: '1.1'
languages:
  java:
    packages:
      zombie.chat:
        ChatSettings:
          modifiers:
          - public
          staticFields:
            infinityRange:
              name: infinityRange
              modifiers:
              - public
              - static
              - final
              type:
                basic: float
          constructors:
          - modifiers:
            - public
          - modifiers:
            - public
            parameters:
            - name: bb
              type:
                basic: ByteBuffer
          methods:
          - name: getFont
            modifiers:
            - public
            return:
              type:
                basic: UIFont
          - name: getFontColor
            modifiers:
            - public
            return:
              type:
                basic: Color
          - name: getFontSize
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getRange
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getZombieAttractionRange
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: isAllowBBcode
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isAllowChatIcons
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isAllowColors
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isAllowFonts
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isAllowImages
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isBold
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isEqualizeLineHeights
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isShowAuthor
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isShowChatTitle
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isShowTimestamp
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isUnique
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isUseOnlyActiveTab
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: pack
            modifiers:
            - public
            parameters:
            - name: bb
              type:
                basic: ByteBufferWriter
            return:
              type:
                basic: void
          - name: setAllowBBcode
            modifiers:
            - public
            parameters:
            - name: allowBBcode
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setAllowChatIcons
            modifiers:
            - public
            parameters:
            - name: allowChatIcons
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setAllowColors
            modifiers:
            - public
            parameters:
            - name: allowColors
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setAllowFonts
            modifiers:
            - public
            parameters:
            - name: allowFonts
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setAllowImages
            modifiers:
            - public
            parameters:
            - name: allowImages
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setBold
            modifiers:
            - public
            parameters:
            - name: bold
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setEqualizeLineHeights
            modifiers:
            - public
            parameters:
            - name: equalizeLineHeights
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setFont
            modifiers:
            - public
            parameters:
            - name: font
              type:
                basic: UIFont
            return:
              type:
                basic: void
          - name: setFontColor
            modifiers:
            - public
            parameters:
            - name: fontColor
              type:
                basic: Color
            return:
              type:
                basic: void
          - name: setFontColor
            modifiers:
            - public
            parameters:
            - name: r
              type:
                basic: float
            - name: g
              type:
                basic: float
            - name: b
              type:
                basic: float
            - name: a
              type:
                basic: float
            return:
              type:
                basic: void
          - name: setFontSize
            modifiers:
            - public
            parameters:
            - name: fontSize
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setRange
            modifiers:
            - public
            parameters:
            - name: range
              type:
                basic: float
            return:
              type:
                basic: void
          - name: setShowAuthor
            modifiers:
            - public
            parameters:
            - name: showAuthor
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setShowChatTitle
            modifiers:
            - public
            parameters:
            - name: showChatTitle
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setShowTimestamp
            modifiers:
            - public
            parameters:
            - name: showTimestamp
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setUnique
            modifiers:
            - public
            parameters:
            - name: unique
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setUseOnlyActiveTab
            modifiers:
            - public
            parameters:
            - name: useOnlyActiveTab
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setZombieAttractionRange
            modifiers:
            - public
            parameters:
            - name: zombieAttractionRange
              type:
                basic: float
            return:
              type:
                basic: void
          javaType: class
          extends: Object
