version: '1.1'
languages:
  java:
    packages:
      zombie.chat:
        ChatSettings.FontSize:
          modifiers:
          - public
          - static
          staticFields:
            Large:
              name: Large
              modifiers:
              - public
              - static
              - final
              type:
                basic: FontSize
            Medium:
              name: Medium
              modifiers:
              - public
              - static
              - final
              type:
                basic: FontSize
            NotDefine:
              name: NotDefine
              modifiers:
              - public
              - static
              - final
              type:
                basic: FontSize
            Small:
              name: Small
              modifiers:
              - public
              - static
              - final
              type:
                basic: FontSize
          staticMethods:
          - name: values
            modifiers:
            - public
            - static
            return:
              type:
                basic: FontSize
              notes: an array containing the constants of this enum class, in the
                order they are declared
            notes: Returns an array containing the constants of this enum class, in
              the order they are declared.
          javaType: enum
          extends: Enum
