version: '1.1'
languages:
  java:
    packages:
      zombie.network:
        ServerSettingsManager:
          modifiers:
          - public
          staticFields:
            instance:
              name: instance
              modifiers:
              - public
              - static
              - final
              type:
                basic: ServerSettingsManager
          constructors:
          - modifiers:
            - public
          methods:
          - name: getNameInSettingsFolder
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
            return:
              type:
                basic: String
          - name: getSettingsByIndex
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
            return:
              type:
                basic: ServerSettings
          - name: getSettingsCount
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getSettingsFolder
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getSuffixes
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
          - name: isValidName
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
            return:
              type:
                basic: boolean
          - name: isValidNewName
            modifiers:
            - public
            parameters:
            - name: newName
              type:
                basic: String
            return:
              type:
                basic: boolean
          - name: readAllSettings
            modifiers:
            - public
            return:
              type:
                basic: void
          javaType: class
          extends: Object
