version: '1.1'
languages:
  java:
    packages:
      zombie.core.opengl:
        PlayerRenderSettings:
          modifiers:
          - public
          - static
          fields:
            CM_Ambient:
              name: CM_Ambient
              modifiers:
              - public
              type:
                basic: float
            CM_DayLightStrength:
              name: CM_DayLightStrength
              modifiers:
              - public
              type:
                basic: float
            CM_Desaturation:
              name: CM_Desaturation
              modifiers:
              - public
              type:
                basic: float
            CM_FogIntensity:
              name: CM_FogIntensity
              modifiers:
              - public
              type:
                basic: float
            CM_GlobalLight:
              name: CM_GlobalLight
              modifiers:
              - public
              type:
                basic: ClimateColorInfo
            CM_GlobalLightIntensity:
              name: CM_GlobalLightIntensity
              modifiers:
              - public
              type:
                basic: float
            CM_NightStrength:
              name: CM_NightStrength
              modifiers:
              - public
              type:
                basic: float
            CM_ViewDistance:
              name: CM_ViewDistance
              modifiers:
              - public
              type:
                basic: float
          constructors:
          - modifiers:
            - public
          methods:
          - name: getAmbient
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getBlendColor
            modifiers:
            - public
            return:
              type:
                basic: Color
          - name: getBlendIntensity
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getBmod
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getDarkness
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getDesaturation
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getFogMod
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getGmod
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getMaskClearColor
            modifiers:
            - public
            return:
              type:
                basic: Color
          - name: getNight
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getRmod
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getSM_Alpha
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getSM_Radius
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getViewDistance
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: isApplyNightVisionGoggles
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isExterior
            modifiers:
            - public
            return:
              type:
                basic: boolean
          javaType: class
          extends: Object
