version: '1.1'
languages:
  java:
    packages:
      zombie.audio:
        MusicIntensityConfig:
          constructors:
          - modifiers:
            - public
          methods:
          - name: checkHealthPanelVisible
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoGameCharacter
                full: zombie.characters.IsoGameCharacter
            return:
              type:
                basic: void
                full: void
          - name: initEvents
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: KahluaTableImpl
                full: se.krka.kahlua.j2se.KahluaTableImpl
            return:
              type:
                basic: void
                full: void
          - name: restoreToFullHealth
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoGameCharacter
                full: zombie.characters.IsoGameCharacter
            return:
              type:
                basic: void
                full: void
          - name: triggerEvent
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: MusicIntensityEvents
                full: zombie.audio.MusicIntensityEvents
            return:
              type:
                basic: MusicIntensityEvent
                full: zombie.audio.MusicIntensityEvent
          staticMethods:
          - name: getInstance
            modifiers:
            - public
            - static
            return:
              type:
                basic: MusicIntensityConfig
                full: zombie.audio.MusicIntensityConfig
          javaType: class
          extends: Object
