version: '1.1'
languages:
  java:
    packages:
      zombie:
        SandboxOptions$MultiplierConfig:
          fields:
            XPMultiplierAiming:
              name: XPMultiplierAiming
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierAxe:
              name: XPMultiplierAxe
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierBlacksmith:
              name: XPMultiplierBlacksmith
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierBlunt:
              name: XPMultiplierBlunt
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierButchering:
              name: XPMultiplierButchering
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierCarving:
              name: XPMultiplierCarving
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierCooking:
              name: XPMultiplierCooking
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierDoctor:
              name: XPMultiplierDoctor
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierElectricity:
              name: XPMultiplierElectricity
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierFarming:
              name: XPMultiplierFarming
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierFishing:
              name: XPMultiplierFishing
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierFitness:
              name: XPMultiplierFitness
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierFlintKnapping:
              name: XPMultiplierFlintKnapping
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierGlassmaking:
              name: XPMultiplierGlassmaking
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierGlobal:
              name: XPMultiplierGlobal
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierGlobalToggle:
              name: XPMultiplierGlobalToggle
              modifiers:
              - public
              - final
              type:
                basic: BooleanSandboxOption
                full: zombie.SandboxOptions$BooleanSandboxOption
                nullable: true
            XPMultiplierHusbandry:
              name: XPMultiplierHusbandry
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierLightfoot:
              name: XPMultiplierLightfoot
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierLongBlade:
              name: XPMultiplierLongBlade
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierMaintenance:
              name: XPMultiplierMaintenance
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierMasonry:
              name: XPMultiplierMasonry
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierMechanics:
              name: XPMultiplierMechanics
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierMetalWelding:
              name: XPMultiplierMetalWelding
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierNimble:
              name: XPMultiplierNimble
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierPlantScavenging:
              name: XPMultiplierPlantScavenging
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierPottery:
              name: XPMultiplierPottery
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierReloading:
              name: XPMultiplierReloading
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierSmallBlade:
              name: XPMultiplierSmallBlade
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierSmallBlunt:
              name: XPMultiplierSmallBlunt
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierSneak:
              name: XPMultiplierSneak
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierSpear:
              name: XPMultiplierSpear
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierSprinting:
              name: XPMultiplierSprinting
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierStrength:
              name: XPMultiplierStrength
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierTailoring:
              name: XPMultiplierTailoring
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierTracking:
              name: XPMultiplierTracking
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierTrapping:
              name: XPMultiplierTrapping
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
            XPMultiplierWoodwork:
              name: XPMultiplierWoodwork
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
                full: zombie.SandboxOptions$DoubleSandboxOption
                nullable: true
          javaType: class
          extends: Object
