version: '1.1'
languages:
  java:
    packages:
      zombie:
        ZombieConfig:
          modifiers:
          - public
          - final
          fields:
            FollowSoundDistance:
              name: FollowSoundDistance
              modifiers:
              - public
              - final
              type:
                basic: IntegerSandboxOption
            PopulationMultiplier:
              name: PopulationMultiplier
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
            PopulationPeakDay:
              name: PopulationPeakDay
              modifiers:
              - public
              - final
              type:
                basic: IntegerSandboxOption
            PopulationPeakMultiplier:
              name: PopulationPeakMultiplier
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
            PopulationStartMultiplier:
              name: PopulationStartMultiplier
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
            RallyGroupRadius:
              name: RallyGroupRadius
              modifiers:
              - public
              - final
              type:
                basic: IntegerSandboxOption
            RallyGroupSeparation:
              name: RallyGroupSeparation
              modifiers:
              - public
              - final
              type:
                basic: IntegerSandboxOption
            RallyGroupSize:
              name: RallyGroupSize
              modifiers:
              - public
              - final
              type:
                basic: IntegerSandboxOption
            RallyTravelDistance:
              name: RallyTravelDistance
              modifiers:
              - public
              - final
              type:
                basic: IntegerSandboxOption
            RedistributeHours:
              name: RedistributeHours
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
            RespawnHours:
              name: RespawnHours
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
            RespawnMultiplier:
              name: RespawnMultiplier
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
            RespawnUnseenHours:
              name: RespawnUnseenHours
              modifiers:
              - public
              - final
              type:
                basic: DoubleSandboxOption
          javaType: class
          extends: Object
