version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.objects:
        Recipe:
          extends: zombie.scripting.objects.BaseScriptObject
          modifiers:
          - public
          fields:
            AllowDestroyedItem:
              name: AllowDestroyedItem
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            AllowFrozenItem:
              name: AllowFrozenItem
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            AllowOnlyOne:
              name: AllowOnlyOne
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            AllowRottenItem:
              name: AllowRottenItem
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            AnimNode:
              name: AnimNode
              modifiers:
              - protected
              type:
                basic: String
                full: java.lang.String
            InSameInventory:
              name: InSameInventory
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            Prop1:
              name: Prop1
              modifiers:
              - protected
              type:
                basic: String
                full: java.lang.String
            Prop2:
              name: Prop2
              modifiers:
              - protected
              type:
                basic: String
                full: java.lang.String
            Result:
              name: Result
              modifiers:
              - public
              type:
                basic: Recipe.Result
                full: zombie.scripting.objects.Recipe$Result
            Results:
              name: Results
              modifiers:
              - public
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.objects.Recipe$Result>
            Sound:
              name: Sound
              modifiers:
              - public
              type:
                basic: String
                full: java.lang.String
            Source:
              name: Source
              modifiers:
              - public
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.objects.Recipe$Source>
            TimeToMake:
              name: TimeToMake
              modifiers:
              - public
              type:
                basic: float
                full: float
            canBeDoneFromFloor:
              name: canBeDoneFromFloor
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            category:
              name: category
              modifiers:
              - protected
              type:
                basic: String
                full: java.lang.String
            heat:
              name: heat
              modifiers:
              - private
              type:
                basic: float
                full: float
            hidden:
              name: hidden
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            luaCalls:
              name: luaCalls
              modifiers:
              - private
              type:
                basic: HashMap
                full: java.util.HashMap<zombie.scripting.objects.Recipe$LuaCall, java.lang.String>
            name:
              name: name
              modifiers:
              - public
              type:
                basic: String
                full: java.lang.String
            needToBeLearn:
              name: needToBeLearn
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            obsolete:
              name: obsolete
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            originalname:
              name: originalname
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            recipeFileText:
              name: recipeFileText
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            removeResultItem:
              name: removeResultItem
              modifiers:
              - protected
              type:
                basic: boolean
                full: boolean
            requiredNearObject:
              name: requiredNearObject
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            requiresWorkstation:
              name: requiresWorkstation
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            skillRequired:
              name: skillRequired
              modifiers:
              - public
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.objects.Recipe$RequiredSkill>
            stationMultiplier:
              name: stationMultiplier
              modifiers:
              - private
              type:
                basic: float
                full: float
            stopOnRun:
              name: stopOnRun
              modifiers:
              - protected
              type:
                basic: boolean
                full: boolean
            stopOnWalk:
              name: stopOnWalk
              modifiers:
              - protected
              type:
                basic: boolean
                full: boolean
            tooltip:
              name: tooltip
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
          constructors:
          - modifiers:
            - public
          methods:
          - name: DoResult
            modifiers:
            - public
            parameters:
            - name: type
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: DoSource
            modifiers:
            - public
            parameters:
            - name: type
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: Load
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: addRequiredSkill
            modifiers:
            - public
            parameters:
            - name: perk
              type:
                basic: PerkFactory.Perk
                full: zombie.characters.skills.PerkFactory$Perk
            - name: level
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: clearRequiredSkills
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: findSource
            modifiers:
            - public
            parameters:
            - name: sourceFullType
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: Recipe.Source
                full: zombie.scripting.objects.Recipe$Source
          - name: getFullType
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getHeat
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getNearItem
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getNumberOfNeededItem
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getOriginalname
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getRequiredSkill
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
                full: int
            return:
              type:
                basic: Recipe.RequiredSkill
                full: zombie.scripting.objects.Recipe$RequiredSkill
          - name: getRequiredSkillCount
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getRequiredSkills
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
          - name: getResult
            modifiers:
            - public
            return:
              type:
                basic: Recipe.Result
                full: zombie.scripting.objects.Recipe$Result
          - name: getResults
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.objects.Recipe$Result>
          - name: getSource
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.scripting.objects.Recipe$Source>
          - name: getStationMultiplier
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: isRequiresWorkstation
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: setNearItem
            modifiers:
            - public
            parameters:
            - name: nearItem
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: setOriginalname
            modifiers:
            - public
            parameters:
            - name: originalname
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
