version: '1.1'
languages:
  java:
    packages:
      zombie.vehicles:
        EditVehicleState.LuaEnvironment:
          modifiers:
          - public
          - static
          - final
          fields:
            caller:
              name: caller
              modifiers:
              - public
              type:
                basic: LuaCaller
            env:
              name: env
              modifiers:
              - public
              type:
                basic: KahluaTable
            platform:
              name: platform
              modifiers:
              - public
              type:
                basic: J2SEPlatform
            thread:
              name: thread
              modifiers:
              - public
              type:
                basic: KahluaThread
          constructors:
          - modifiers:
            - public
            parameters:
            - name: platform
              type:
                basic: J2SEPlatform
            - name: converterManager
              type:
                basic: KahluaConverterManager
            - name: env
              type:
                basic: KahluaTable
          javaType: class
          extends: Object
