version: '1.1'
languages:
  java:
    packages:
      zombie.erosion:
        ErosionConfig:
          modifiers:
          - public
          - final
          fields:
            debug:
              name: debug
              modifiers:
              - public
              - final
              type:
                basic: Debug
            season:
              name: season
              modifiers:
              - public
              - final
              type:
                basic: Season
            seeds:
              name: seeds
              modifiers:
              - public
              - final
              type:
                basic: Seeds
            time:
              name: time
              modifiers:
              - public
              - final
              type:
                basic: Time
          constructors:
          - modifiers:
            - public
          methods:
          - name: consolePrint
            modifiers:
            - public
            return:
              type:
                basic: void
          - name: getDebug
            modifiers:
            - public
            return:
              type:
                basic: Debug
          - name: load
            modifiers:
            - public
            parameters:
            - name: bb
              type:
                basic: ByteBuffer
            return:
              type:
                basic: void
          - name: readFile
            modifiers:
            - public
            parameters:
            - name: _file
              type:
                basic: String
            return:
              type:
                basic: boolean
          - name: save
            modifiers:
            - public
            parameters:
            - name: bb
              type:
                basic: ByteBuffer
            return:
              type:
                basic: void
          - name: writeFile
            modifiers:
            - public
            parameters:
            - name: _file
              type:
                basic: String
            return:
              type:
                basic: void
          javaType: class
          extends: Object
