version: '1.1'
languages:
  java:
    packages:
      zombie.erosion:
        ErosionConfig.Time:
          modifiers:
          - public
          - static
          - final
          constructors:
          - modifiers:
            - public
          javaType: class
          extends: Object
