version: '1.1'
languages:
  java:
    packages:
      java.lang:
        Package:
          methods:
          - name: __toString__
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getAnnotation
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<A>
                full: java.lang.Class<A>
            return:
              type:
                basic: A
                full: A
          - name: getAnnotation
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<T>
                full: java.lang.Class<T>
            return:
              type:
                basic: T
                full: T
          - name: getAnnotations
            modifiers:
            - public
            return:
              type:
                basic: Annotation[]
                full: java.lang.annotation.Annotation[]
          - name: getAnnotations
            modifiers:
            - public
            return:
              type:
                basic: Annotation[]
                full: java.lang.annotation.Annotation[]
          - name: getAnnotationsByType
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<A>
                full: java.lang.Class<A>
            return:
              type:
                basic: A[]
                full: A[]
          - name: getAnnotationsByType
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<T>
                full: java.lang.Class<T>
            return:
              type:
                basic: T[]
                full: T[]
          - name: getDeclaredAnnotation
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<A>
                full: java.lang.Class<A>
            return:
              type:
                basic: A
                full: A
          - name: getDeclaredAnnotation
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<T>
                full: java.lang.Class<T>
            return:
              type:
                basic: T
                full: T
          - name: getDeclaredAnnotations
            modifiers:
            - public
            return:
              type:
                basic: Annotation[]
                full: java.lang.annotation.Annotation[]
          - name: getDeclaredAnnotations
            modifiers:
            - public
            return:
              type:
                basic: Annotation[]
                full: java.lang.annotation.Annotation[]
          - name: getDeclaredAnnotationsByType
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<A>
                full: java.lang.Class<A>
            return:
              type:
                basic: A[]
                full: A[]
          - name: getDeclaredAnnotationsByType
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<T>
                full: java.lang.Class<T>
            return:
              type:
                basic: T[]
                full: T[]
          - name: getImplementationTitle
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getImplementationVendor
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getImplementationVersion
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getSpecificationTitle
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getSpecificationVendor
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getSpecificationVersion
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: hashCode
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: isAnnotationPresent
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<? extends Annotation>
                full: java.lang.Class<? extends java.lang.annotation.Annotation>
            return:
              type:
                basic: boolean
                full: boolean
          - name: isAnnotationPresent
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Class<? extends Annotation>
                full: java.lang.Class<? extends java.lang.annotation.Annotation>
            return:
              type:
                basic: boolean
                full: boolean
          - name: isCompatibleWith
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: isSealed
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isSealed
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: URL
                full: java.net.URL
            return:
              type:
                basic: boolean
                full: boolean
          staticMethods:
          - name: getPackage
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: Package
                full: java.lang.Package
            deprecated: true
          - name: getPackages
            modifiers:
            - public
            - static
            return:
              type:
                basic: Package[]
                full: java.lang.Package[]
          javaType: class
          extends: NamedPackage
