version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemContainer.CategoryPredicate:
          extends: java.lang.Object
          modifiers:
          - package
          - final
          fields:
            category:
              name: category
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
          constructors:
          - modifiers:
            - private
          methods:
          - name: init
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: ItemContainer.CategoryPredicate
                full: zombie.inventory.ItemContainer$CategoryPredicate
          - name: test
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            return:
              type:
                basic: boolean
                full: boolean
          - name: test
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
