version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemSpawner:
          constructors:
          - modifiers:
            - public
          staticMethods:
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            - name: arg1
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            - name: arg1
              type:
                basic: IsoGridSquare
                full: zombie.iso.IsoGridSquare
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            - name: arg2
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            - name: arg1
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            - name: arg2
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            - name: arg1
              type:
                basic: IsoGridSquare
                full: zombie.iso.IsoGridSquare
            - name: arg2
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: IsoGridSquare
                full: zombie.iso.IsoGridSquare
            - name: arg2
              type:
                basic: float
                full: float
            - name: arg3
              type:
                basic: float
                full: float
            - name: arg4
              type:
                basic: float
                full: float
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            - name: arg1
              type:
                basic: IsoGridSquare
                full: zombie.iso.IsoGridSquare
            - name: arg2
              type:
                basic: float
                full: float
            - name: arg3
              type:
                basic: float
                full: float
            - name: arg4
              type:
                basic: float
                full: float
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: IsoGridSquare
                full: zombie.iso.IsoGridSquare
            - name: arg2
              type:
                basic: float
                full: float
            - name: arg3
              type:
                basic: float
                full: float
            - name: arg4
              type:
                basic: float
                full: float
            - name: arg5
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItem
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            - name: arg1
              type:
                basic: IsoGridSquare
                full: zombie.iso.IsoGridSquare
            - name: arg2
              type:
                basic: float
                full: float
            - name: arg3
              type:
                basic: float
                full: float
            - name: arg4
              type:
                basic: float
                full: float
            - name: arg5
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
          - name: spawnItems
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            return:
              type:
                basic: List<InventoryItem>
                full: java.util.List<zombie.inventory.InventoryItem>
          - name: spawnItems
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            return:
              type:
                basic: List<InventoryItem>
                full: java.util.List<zombie.inventory.InventoryItem>
          javaType: class
          extends: Object
