version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemContainer.InventoryItemListPool:
          extends: zombie.popman.ObjectPool<zombie.inventory.ItemContainer$InventoryItemList>
          modifiers:
          - package
          - final
          constructors:
          - modifiers:
            - public
          methods:
          - name: release
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ItemContainer.InventoryItemList
                full: zombie.inventory.ItemContainer$InventoryItemList
            return:
              type:
                basic: void
                full: void
          - name: release
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: void
                full: void
