version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemPickerJava.ItemPickerContainer:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            Items:
              name: Items
              modifiers:
              - public
              type:
                basic: ItemPickerJava.ItemPickerItem
                full: zombie.inventory.ItemPickerJava$ItemPickerItem[]
            bags:
              name: bags
              modifiers:
              - public
              type:
                basic: ItemPickerJava.ItemPickerContainer
                full: zombie.inventory.ItemPickerJava$ItemPickerContainer
            canBurn:
              name: canBurn
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            cookFood:
              name: cookFood
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            defaultInventoryLoot:
              name: defaultInventoryLoot
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            dontSpawnAmmo:
              name: dontSpawnAmmo
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            fillRand:
              name: fillRand
              modifiers:
              - public
              type:
                basic: int
                full: int
            ignoreZombieDensity:
              name: ignoreZombieDensity
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            isRotten:
              name: isRotten
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            isShop:
              name: isShop
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            isTrash:
              name: isTrash
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            isWorn:
              name: isWorn
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            junk:
              name: junk
              modifiers:
              - public
              type:
                basic: ItemPickerJava.ItemPickerContainer
                full: zombie.inventory.ItemPickerJava$ItemPickerContainer
            maxMap:
              name: maxMap
              modifiers:
              - public
              type:
                basic: int
                full: int
            noAutoAge:
              name: noAutoAge
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            onlyOne:
              name: onlyOne
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            procedural:
              name: procedural
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            proceduralItems:
              name: proceduralItems
              modifiers:
              - public
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.inventory.ItemPickerJava$ProceduralItem>
            rolls:
              name: rolls
              modifiers:
              - public
              type:
                basic: float
                full: float
            stashChance:
              name: stashChance
              modifiers:
              - public
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
          methods:
          - name: compact
            modifiers:
            - package
            return:
              type:
                basic: void
                full: void
