version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemContainer.Comparators:
          extends: java.lang.Object
          modifiers:
          - package
          - final
          fields:
            condition:
              name: condition
              modifiers:
              - package
              type:
                basic: ObjectPool
                full: zombie.popman.ObjectPool<zombie.inventory.ItemContainer$ConditionComparator>
            eval:
              name: eval
              modifiers:
              - package
              type:
                basic: ObjectPool
                full: zombie.popman.ObjectPool<zombie.inventory.ItemContainer$EvalComparator>
            evalArg:
              name: evalArg
              modifiers:
              - package
              type:
                basic: ObjectPool
                full: zombie.popman.ObjectPool<zombie.inventory.ItemContainer$EvalArgComparator>
          constructors:
          - modifiers:
            - private
