version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemContainer.TagEvalArgPredicate:
          extends: java.lang.Object
          modifiers:
          - package
          - final
          fields:
            arg:
              name: arg
              modifiers:
              - private
              type:
                basic: Object
                full: java.lang.Object
            functionObj:
              name: functionObj
              modifiers:
              - private
              type:
                basic: LuaClosure
                full: se.krka.kahlua.vm.LuaClosure
            tag:
              name: tag
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
          constructors:
          - modifiers:
            - private
          methods:
          - name: init
            modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: LuaClosure
                full: se.krka.kahlua.vm.LuaClosure
            - name: arg2
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: ItemContainer.TagEvalArgPredicate
                full: zombie.inventory.ItemContainer$TagEvalArgPredicate
          - name: test
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            return:
              type:
                basic: boolean
                full: boolean
          - name: test
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
