version: '1.1'
languages:
  java:
    packages:
      zombie.network:
        ServerSettings:
          modifiers:
          - public
          constructors:
          - modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
          methods:
          - name: addSpawnRegion
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
            - name: file
              type:
                basic: String
            return:
              type:
                basic: void
          - name: clearSpawnRegions
            modifiers:
            - public
            return:
              type:
                basic: void
          - name: deleteFiles
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: duplicateFiles
            modifiers:
            - public
            parameters:
            - name: newName
              type:
                basic: String
            return:
              type:
                basic: boolean
          - name: getErrorMsg
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getNumSpawnRegions
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getSandboxOptions
            modifiers:
            - public
            return:
              type:
                basic: SandboxOptions
          - name: getServerOptions
            modifiers:
            - public
            return:
              type:
                basic: ServerOptions
          - name: getSpawnRegionFile
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
            return:
              type:
                basic: String
          - name: getSpawnRegionName
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
            return:
              type:
                basic: String
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: loadFiles
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: loadSpawnPointsFile
            modifiers:
            - public
            parameters:
            - name: file
              type:
                basic: String
            return:
              type:
                basic: KahluaTable
          - name: removeSpawnRegion
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
            return:
              type:
                basic: void
          - name: rename
            modifiers:
            - public
            parameters:
            - name: newName
              type:
                basic: String
            return:
              type:
                basic: boolean
          - name: resetToDefault
            modifiers:
            - public
            return:
              type:
                basic: void
          - name: saveFiles
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: saveSpawnPointsFile
            modifiers:
            - public
            parameters:
            - name: file
              type:
                basic: String
            - name: professionsTable
              type:
                basic: KahluaTable
            return:
              type:
                basic: boolean
          javaType: class
          extends: Object
