version: '1.1'
languages:
  java:
    packages:
      zombie.entity.util:
        ObjectMap.Values:
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ObjectMap<?, V>
                full: zombie.entity.util.ObjectMap<?, V>
          methods:
          - name: hasNext
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: iterator
            modifiers:
            - public
            return:
              type:
                basic: Iterator
                full: java.util.Iterator
          - name: iterator
            modifiers:
            - public
            return:
              type:
                basic: Iterator
                full: java.util.Iterator
          - name: next
            modifiers:
            - public
            return:
              type:
                basic: V
                full: V
          - name: remove
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: reset
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: toArray
            modifiers:
            - public
            return:
              type:
                basic: Array<V>
                full: zombie.entity.util.Array<V>
          - name: toArray
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Array<V>
                full: zombie.entity.util.Array<V>
            return:
              type:
                basic: Array<V>
                full: zombie.entity.util.Array<V>
          javaType: class
          extends: ObjectMap.MapIterator<Object, V, V>
