version: '1.1'
languages:
  java:
    packages:
      zombie.core.physics:
        RagdollControllerDebugRenderer.DebugDrawSettings:
          constructors:
          - modifiers:
            - public
          javaType: class
          extends: Object
