version: '1.1'
languages:
  java:
    packages:
      zombie.core.physics:
        RagdollSettingsManager$HitReactionSetting:
          constructors:
          - modifiers:
            - public
          methods:
          - name: getAdminValue
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getMax
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getMin
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: init
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            - name: arg2
              type:
                basic: float
                full: float
            - name: arg3
              type:
                basic: float
                full: float
            - name: arg4
              type:
                basic: float
                full: float
            return:
              type:
                basic: HitReactionSetting
                full: zombie.core.physics.RagdollSettingsManager$HitReactionSetting
          - name: isEnableAdmin
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: reset
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: setAdminValue
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setEnableAdmin
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          javaType: class
          extends: Object
