version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.ui:
        UiConfig:
          methods:
          - name: getEntityDisplayName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getEntityStyleName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getEntityUiStyle
            modifiers:
            - public
            return:
              type:
                basic: EntityUiStyle
                full: zombie.scripting.ui.XuiSkin$EntityUiStyle
          - name: getSkin
            modifiers:
            - public
            return:
              type:
                basic: XuiSkin
                full: zombie.scripting.ui.XuiSkin
          - name: getSkin
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: XuiSkin
                full: zombie.scripting.ui.XuiSkin
          - name: getSkinOrDefault
            modifiers:
            - public
            return:
              type:
                basic: XuiSkin
                full: zombie.scripting.ui.XuiSkin
          - name: isUiEnabled
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          javaType: class
          extends: Component
