version: '1.1'
languages:
  java:
    packages:
      javax.swing:
        Action:
          extends: java.lang.Object
          modifiers:
          - public
          - abstract
          staticFields:
            ACCELERATOR_KEY:
              name: ACCELERATOR_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing a KeyStroke to be used as the\n accelerator\
                \ for the action."
            ACTION_COMMAND_KEY:
              name: ACTION_COMMAND_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used to determine the command String for the\n ActionEvent\
                \ that will be created when an\n Action is going to be notified as\
                \ the result of\n residing in a Keymap associated with a\n JComponent."
            DEFAULT:
              name: DEFAULT
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: Not currently used.
            DISPLAYED_MNEMONIC_INDEX_KEY:
              name: DISPLAYED_MNEMONIC_INDEX_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing an Integer that corresponds\n to the\
                \ index in the text (identified by the NAME\n property) that the decoration\
                \ for a mnemonic should be rendered at.  If\n the value of this property\
                \ is greater than or equal to the length of\n the text, it will treated\
                \ as -1.\n \n Note: the value of this field is prefixed with 'Swing'\
                \ to\n avoid possible collisions with existing Actions."
            LARGE_ICON_KEY:
              name: LARGE_ICON_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing an Icon.  This is typically\n used\
                \ by buttons, such as JButton and\n JToggleButton.\n \n If the same\
                \ Action is used with menus and buttons you'll\n typically specify\
                \ both a SMALL_ICON and a\n LARGE_ICON_KEY.  The menu will use the\n\
                \ SMALL_ICON and the button the LARGE_ICON_KEY.\n \n Note: the value\
                \ of this field is prefixed with 'Swing' to\n avoid possible collisions\
                \ with existing Actions."
            LONG_DESCRIPTION:
              name: LONG_DESCRIPTION
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing a longer String\n description for the\
                \ action, could be used for context-sensitive help."
            MNEMONIC_KEY:
              name: MNEMONIC_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing an Integer that corresponds to\n one\
                \ of the KeyEvent key codes.  The value is\n commonly used to specify\
                \ a mnemonic.  For example:\n myAction.putValue(Action.MNEMONIC_KEY,\
                \ KeyEvent.VK_A)\n sets the mnemonic of myAction to 'a', while\n myAction.putValue(Action.MNEMONIC_KEY,\
                \ KeyEvent.getExtendedKeyCodeForChar('\u0444'))\n sets the mnemonic\
                \ of myAction to Cyrillic letter \"Ef\"."
            NAME:
              name: NAME
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing the String name\n for the action, used\
                \ for a menu or button."
            SELECTED_KEY:
              name: SELECTED_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing a Boolean that corresponds\n to the\
                \ selected state.  This is typically used only for components\n that\
                \ have a meaningful selection state.  For example,\n JRadioButton\
                \ and JCheckBox make use of\n this but instances of JMenu don't.\n\
                \ \n This property differs from the others in that it is both read\n\
                \ by the component and set by the component.  For example,\n if an\
                \ Action is attached to a JCheckBox\n the selected state of the JCheckBox\
                \ will be set from\n that of the Action.  If the user clicks on the\n\
                \ JCheckBox the selected state of the JCheckBox\n and the Action will\
                \ both be updated.\n \n Note: the value of this field is prefixed\
                \ with 'Swing' to\n avoid possible collisions with existing Actions."
            SHORT_DESCRIPTION:
              name: SHORT_DESCRIPTION
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing a short String\n description for the\
                \ action, used for tooltip text."
            SMALL_ICON:
              name: SMALL_ICON
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
              notes: "The key used for storing a small Icon, such\n as ImageIcon.\
                \  This is typically used with\n menus such as JMenuItem.\n \n If\
                \ the same Action is used with menus and buttons you'll\n typically\
                \ specify both a SMALL_ICON and a\n LARGE_ICON_KEY.  The menu will\
                \ use the\n SMALL_ICON and the button will use the\n LARGE_ICON_KEY."
          methods:
          - name: accept
            modifiers:
            - public
            parameters:
            - name: sender
              type:
                basic: Object
                full: java.lang.Object
              notes: the object to check, can be null
            return:
              type:
                basic: boolean
                full: boolean
              notes: "true if the action should be performed with the sender\n   \
                \      object, must be false if the action is disabled."
            notes: "Determines whether the action should be performed with the specified\n\
              \ sender object. The sender can be null.\n The method must return false\
              \ if the action is disabled."
          - name: addPropertyChangeListener
            modifiers:
            - public
            - abstract
            parameters:
            - name: listener
              type:
                basic: PropertyChangeListener
                full: java.beans.PropertyChangeListener
              notes: a PropertyChangeListener object
            return:
              type:
                basic: void
                full: void
            notes: "Adds a PropertyChange listener. Containers and attached\n components\
              \ use these methods to register interest in this\n Action object. When\
              \ its enabled state or other property\n changes, the registered listeners\
              \ are informed of the change."
          - name: getValue
            modifiers:
            - public
            - abstract
            parameters:
            - name: key
              type:
                basic: String
                full: java.lang.String
              notes: a String containing the key
            return:
              type:
                basic: Object
                full: java.lang.Object
              notes: the Object value
            notes: "Gets one of this object's properties\n using the associated key."
          - name: isEnabled
            modifiers:
            - public
            - abstract
            return:
              type:
                basic: boolean
                full: boolean
              notes: true if this Action is enabled
            notes: "Returns the enabled state of the Action. When enabled,\n any component\
              \ associated with this object is active and\n able to fire this object's\
              \ actionPerformed method."
          - name: putValue
            modifiers:
            - public
            - abstract
            parameters:
            - name: key
              type:
                basic: String
                full: java.lang.String
              notes: a String containing the key
            - name: value
              type:
                basic: Object
                full: java.lang.Object
              notes: an Object value
            return:
              type:
                basic: void
                full: void
            notes: "Sets one of this object's properties\n using the associated key.\
              \ If the value has\n changed, a PropertyChangeEvent is sent\n to listeners."
          - name: removePropertyChangeListener
            modifiers:
            - public
            - abstract
            parameters:
            - name: listener
              type:
                basic: PropertyChangeListener
                full: java.beans.PropertyChangeListener
              notes: a PropertyChangeListener object
            return:
              type:
                basic: void
                full: void
            notes: Removes a PropertyChange listener.
          - name: setEnabled
            modifiers:
            - public
            - abstract
            parameters:
            - name: b
              type:
                basic: boolean
                full: boolean
              notes: true to enable this Action, false to disable it
            return:
              type:
                basic: void
                full: void
            notes: "Sets the enabled state of the Action.  When enabled,\n any component\
              \ associated with this object is active and\n able to fire this object's\
              \ actionPerformed method.\n If the value has changed, a PropertyChangeEvent\
              \ is sent\n to listeners."
