version: '1.1'
languages:
  java:
    packages:
      java.awt:
        GraphicsConfigTemplate:
          staticFields:
            PREFERRED:
              name: PREFERRED
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            REQUIRED:
              name: REQUIRED
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            UNNECESSARY:
              name: UNNECESSARY
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
          constructors:
          - modifiers:
            - public
          methods:
          - name: getBestConfiguration
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: GraphicsConfiguration[]
                full: java.awt.GraphicsConfiguration[]
            return:
              type:
                basic: GraphicsConfiguration
                full: java.awt.GraphicsConfiguration
          - name: isGraphicsConfigSupported
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: GraphicsConfiguration
                full: java.awt.GraphicsConfiguration
            return:
              type:
                basic: boolean
                full: boolean
          javaType: class
          extends: Object
