version: '1.1'
languages:
  java:
    packages:
      zombie.config:
        ArrayConfigOption:
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: ConfigOption
                full: zombie.config.ConfigOption
            - name: arg2
              type:
                basic: String
                full: java.lang.String
            - name: arg3
              type:
                basic: String
                full: java.lang.String
          methods:
          - name: clear
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: getElement
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: ConfigOption
                full: zombie.config.ConfigOption
          - name: getElementAsDouble
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            - name: arg1
              type:
                basic: float
                full: float
            return:
              type:
                basic: double
                full: double
          - name: getTooltip
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getType
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getValueAsColorInfo
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ColorInfo
                full: zombie.core.textures.ColorInfo
            return:
              type:
                basic: ColorInfo
                full: zombie.core.textures.ColorInfo
          - name: getValueAsObject
            modifiers:
            - public
            return:
              type:
                basic: Object
                full: java.lang.Object
          - name: getValueAsString
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: isMultiLine
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValidString
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: makeCopy
            modifiers:
            - public
            return:
              type:
                basic: ConfigOption
                full: zombie.config.ConfigOption
          - name: parse
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: resetToDefault
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: setDefaultToCurrentValue
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: setFixedSize
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: ArrayConfigOption
                full: zombie.config.ArrayConfigOption
          - name: setMultiLine
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: ArrayConfigOption
                full: zombie.config.ArrayConfigOption
          - name: setValueFromObject
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: void
                full: void
          - name: setValueVarArgs
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object[]
                full: java.lang.Object[]
            return:
              type:
                basic: ArrayConfigOption
                full: zombie.config.ArrayConfigOption
          - name: size
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          javaType: class
          extends: ConfigOption
