version: '1.1'
languages:
  java:
    packages:
      zombie.config:
        EnumConfigOption:
          modifiers:
          - public
          constructors:
          - modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
            - name: numValues
              type:
                basic: int
            - name: defaultValue
              type:
                basic: int
          methods:
          - name: getNumValues
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getType
            modifiers:
            - public
            return:
              type:
                basic: String
          javaType: class
          extends: IntegerConfigOption
