version: '1.1'
languages:
  java:
    packages:
      zombie.config:
        StringConfigOption:
          modifiers:
          - public
          constructors:
          - modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
            - name: defaultValue
              type:
                basic: String
            - name: maxLength
              type:
                basic: int
          methods:
          - name: getDefaultValue
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getTooltip
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getType
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getValue
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getValueAsLuaString
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getValueAsObject
            modifiers:
            - public
            return:
              type:
                basic: Object
          - name: getValueAsString
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: isValidString
            modifiers:
            - public
            parameters:
            - name: s
              type:
                basic: String
            return:
              type:
                basic: boolean
          - name: parse
            modifiers:
            - public
            parameters:
            - name: s
              type:
                basic: String
            return:
              type:
                basic: void
          - name: resetToDefault
            modifiers:
            - public
            return:
              type:
                basic: void
          - name: setDefaultToCurrentValue
            modifiers:
            - public
            return:
              type:
                basic: void
          - name: setValue
            modifiers:
            - public
            parameters:
            - name: value
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setValueFromObject
            modifiers:
            - public
            parameters:
            - name: o
              type:
                basic: Object
            return:
              type:
                basic: void
          javaType: class
          extends: ConfigOption
