version: '1.1'
languages:
  java:
    packages:
      zombie.inventory.types:
        Clothing.WetDryState:
          extends: java.lang.Enum<zombie.inventory.types.Clothing$WetDryState>
          modifiers:
          - package
          - final
          staticFields:
            $VALUES:
              name: $VALUES
              modifiers:
              - private
              - static
              type:
                basic: Clothing.WetDryState
                full: zombie.inventory.types.Clothing$WetDryState[]
            Dryer:
              name: Dryer
              modifiers:
              - public
              - static
              type:
                basic: Clothing.WetDryState
                full: zombie.inventory.types.Clothing$WetDryState
            Invalid:
              name: Invalid
              modifiers:
              - public
              - static
              type:
                basic: Clothing.WetDryState
                full: zombie.inventory.types.Clothing$WetDryState
            Wetter:
              name: Wetter
              modifiers:
              - public
              - static
              type:
                basic: Clothing.WetDryState
                full: zombie.inventory.types.Clothing$WetDryState
          constructors:
          - modifiers:
            - private
          staticMethods:
          - name: $values
            modifiers:
            - private
            - static
            return:
              type:
                basic: Clothing.WetDryState
                full: zombie.inventory.types.Clothing$WetDryState[]
          - name: valueOf
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: Clothing.WetDryState
                full: zombie.inventory.types.Clothing$WetDryState
          - name: values
            modifiers:
            - public
            - static
            return:
              type:
                basic: Clothing.WetDryState
                full: zombie.inventory.types.Clothing$WetDryState[]
