version: '1.1'
languages:
  java:
    packages:
      zombie.inventory.types:
        WeaponPart:
          extends: zombie.inventory.InventoryItem
          modifiers:
          - public
          - final
          fields:
            aimingTime:
              name: aimingTime
              modifiers:
              - private
              type:
                basic: int
                full: int
            angle:
              name: angle
              modifiers:
              - private
              type:
                basic: float
                full: float
            canAttachCallback:
              name: canAttachCallback
              modifiers:
              - package
              type:
                basic: String
                full: java.lang.String
            canDetachCallback:
              name: canDetachCallback
              modifiers:
              - package
              type:
                basic: String
                full: java.lang.String
            clipSize:
              name: clipSize
              modifiers:
              - private
              type:
                basic: int
                full: int
            damage:
              name: damage
              modifiers:
              - private
              type:
                basic: float
                full: float
            hitChance:
              name: hitChance
              modifiers:
              - private
              type:
                basic: int
                full: int
            lastUpdateMinutes:
              name: lastUpdateMinutes
              modifiers:
              - protected
              type:
                basic: int
                full: int
            lowLightBonus:
              name: lowLightBonus
              modifiers:
              - private
              type:
                basic: float
                full: float
            maxRange:
              name: maxRange
              modifiers:
              - private
              type:
                basic: float
                full: float
            maxSightRange:
              name: maxSightRange
              modifiers:
              - private
              type:
                basic: float
                full: float
            minRangeRanged:
              name: minRangeRanged
              modifiers:
              - private
              type:
                basic: float
                full: float
            minSightRange:
              name: minSightRange
              modifiers:
              - private
              type:
                basic: float
                full: float
            mountOn:
              name: mountOn
              modifiers:
              - private
              type:
                basic: List
                full: java.util.List<java.lang.String>
            mountOnDisplayName:
              name: mountOnDisplayName
              modifiers:
              - private
              type:
                basic: List
                full: java.util.List<java.lang.String>
            onAttachCallback:
              name: onAttachCallback
              modifiers:
              - package
              type:
                basic: String
                full: java.lang.String
            onDetachCallback:
              name: onDetachCallback
              modifiers:
              - package
              type:
                basic: String
                full: java.lang.String
            partType:
              name: partType
              modifiers:
              - private
              type:
                basic: String
                full: java.lang.String
            recoilDelay:
              name: recoilDelay
              modifiers:
              - private
              type:
                basic: float
                full: float
            reloadTime:
              name: reloadTime
              modifiers:
              - private
              type:
                basic: int
                full: int
            spreadModifier:
              name: spreadModifier
              modifiers:
              - private
              type:
                basic: float
                full: float
            ticks:
              name: ticks
              modifiers:
              - protected
              type:
                basic: float
                full: float
            useDelta:
              name: useDelta
              modifiers:
              - protected
              type:
                basic: float
                full: float
            weightModifier:
              name: weightModifier
              modifiers:
              - private
              type:
                basic: float
                full: float
          constructors:
          - modifiers:
            - public
            parameters:
            - name: module
              type:
                basic: String
                full: java.lang.String
            - name: name
              type:
                basic: String
                full: java.lang.String
            - name: itemType
              type:
                basic: String
                full: java.lang.String
            - name: texName
              type:
                basic: String
                full: java.lang.String
          methods:
          - name: DoBatteryTooltip
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ObjectTooltip
                full: zombie.ui.ObjectTooltip
            - name: arg1
              type:
                basic: ObjectTooltip.Layout
                full: zombie.ui.ObjectTooltip$Layout
            return:
              type:
                basic: void
                full: void
          - name: DoTooltip
            modifiers:
            - public
            parameters:
            - name: tooltipUI
              type:
                basic: ObjectTooltip
                full: zombie.ui.ObjectTooltip
            - name: layout
              type:
                basic: ObjectTooltip.Layout
                full: zombie.ui.ObjectTooltip$Layout
            return:
              type:
                basic: void
                full: void
          - name: canAttach
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoGameCharacter
                full: zombie.characters.IsoGameCharacter
            - name: arg1
              type:
                basic: HandWeapon
                full: zombie.inventory.types.HandWeapon
            return:
              type:
                basic: boolean
                full: boolean
          - name: canDetach
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoGameCharacter
                full: zombie.characters.IsoGameCharacter
            - name: arg1
              type:
                basic: HandWeapon
                full: zombie.inventory.types.HandWeapon
            return:
              type:
                basic: boolean
                full: boolean
          - name: getAimingTime
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getAngle
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getCategory
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getClipSize
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getCurrentUsesFloat
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getDamage
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getHitChance
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLowLightBonus
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getMaxRange
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getMaxSightRange
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getMaxUses
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMinRangeRanged
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getMinSightRange
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getMountOn
            modifiers:
            - public
            return:
              type:
                basic: List
                full: java.util.List<java.lang.String>
          - name: getPartType
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getRecoilDelay
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getReloadTime
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getSaveType
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getSpreadModifier
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getWeightModifier
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: onAttach
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoGameCharacter
                full: zombie.characters.IsoGameCharacter
            - name: arg1
              type:
                basic: HandWeapon
                full: zombie.inventory.types.HandWeapon
            return:
              type:
                basic: void
                full: void
          - name: onDetach
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoGameCharacter
                full: zombie.characters.IsoGameCharacter
            - name: arg1
              type:
                basic: HandWeapon
                full: zombie.inventory.types.HandWeapon
            return:
              type:
                basic: void
                full: void
          - name: render
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: setAimingTime
            modifiers:
            - public
            parameters:
            - name: aimingTime
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setAngle
            modifiers:
            - public
            parameters:
            - name: angle
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setCanAttachCallback
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: setCanDetachCallback
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: setClipSize
            modifiers:
            - public
            parameters:
            - name: clipSize
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setCurrentUsesFloat
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setDamage
            modifiers:
            - public
            parameters:
            - name: damage
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setHitChance
            modifiers:
            - public
            parameters:
            - name: hitChance
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setLowLightBonus
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setMaxRange
            modifiers:
            - public
            parameters:
            - name: maxRange
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setMaxSightRange
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setMinRangeRanged
            modifiers:
            - public
            parameters:
            - name: minRangeRanged
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setMinSightRange
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setMountOn
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: List
                full: java.util.List<java.lang.String>
            return:
              type:
                basic: void
                full: void
          - name: setOnAttachCallback
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: setOnDetachCallback
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: setPartType
            modifiers:
            - public
            parameters:
            - name: partType
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: setRecoilDelay
            modifiers:
            - public
            parameters:
            - name: recoilDelay
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setReloadTime
            modifiers:
            - public
            parameters:
            - name: reloadTime
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: setSpreadModifier
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setUseDelta
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setUsedDelta
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: setWeightModifier
            modifiers:
            - public
            parameters:
            - name: weightModifier
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: update
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
