version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.ui:
        UiConfigScript:
          methods:
          - name: InitLoadPP
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
          - name: OnLoadedAfterLua
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: OnPostWorldDictionaryInit
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: OnScriptsLoaded
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ScriptLoadMode
                full: zombie.scripting.ScriptLoadMode
            return:
              type:
                basic: void
                full: void
          - name: PreReload
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: getDisplayNameDebug
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getEntityStyle
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getXuiSkinName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: isUiEnabled
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isoMasterOnly
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: reset
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          javaType: class
          extends: ComponentScript
