version: '1.1'
languages:
  java:
    packages:
      zombie.iso.worldgen.veins:
        OreVeinConfig:
          constructors:
          - modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: List<TileGroup>
                full: java.util.List<zombie.iso.worldgen.biomes.TileGroup>
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: float
                full: float
            - name: arg3
              type:
                basic: int
                full: int
            - name: arg4
              type:
                basic: int
                full: int
            - name: arg5
              type:
                basic: int
                full: int
            - name: arg6
              type:
                basic: int
                full: int
            - name: arg7
              type:
                basic: int
                full: int
            - name: arg8
              type:
                basic: float
                full: float
            - name: arg9
              type:
                basic: float
                full: float
          methods:
          - name: getArmsAmountMax
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsAmountMin
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsDeltaAngle
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsDistMax
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsDistMin
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getArmsProb
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getCenterProb
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getCenterRadius
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getProbability
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getTiles
            modifiers:
            - public
            return:
              type:
                basic: List<TileGroup>
                full: java.util.List<zombie.iso.worldgen.biomes.TileGroup>
          javaType: class
          extends: Object
