version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.spriteconfig:
        SpriteConfigManager:
          staticFields:
            FACE_E:
              name: FACE_E
              modifiers:
              - public
              - static
              - final
              type:
                basic: String
                full: java.lang.String
                nullable: true
            FACE_ID_CARDINAL_MAX:
              name: FACE_ID_CARDINAL_MAX
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_ID_E:
              name: FACE_ID_E
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_ID_MAX:
              name: FACE_ID_MAX
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_ID_N:
              name: FACE_ID_N
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_ID_N_OPEN:
              name: FACE_ID_N_OPEN
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_ID_S:
              name: FACE_ID_S
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_ID_SINGLE:
              name: FACE_ID_SINGLE
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_ID_W:
              name: FACE_ID_W
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_ID_W_OPEN:
              name: FACE_ID_W_OPEN
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
            FACE_N:
              name: FACE_N
              modifiers:
              - public
              - static
              - final
              type:
                basic: String
                full: java.lang.String
                nullable: true
            FACE_N_OPEN:
              name: FACE_N_OPEN
              modifiers:
              - public
              - static
              - final
              type:
                basic: String
                full: java.lang.String
                nullable: true
            FACE_S:
              name: FACE_S
              modifiers:
              - public
              - static
              - final
              type:
                basic: String
                full: java.lang.String
                nullable: true
            FACE_SINGLE:
              name: FACE_SINGLE
              modifiers:
              - public
              - static
              - final
              type:
                basic: String
                full: java.lang.String
                nullable: true
            FACE_W:
              name: FACE_W
              modifiers:
              - public
              - static
              - final
              type:
                basic: String
                full: java.lang.String
                nullable: true
            FACE_W_OPEN:
              name: FACE_W_OPEN
              modifiers:
              - public
              - static
              - final
              type:
                basic: String
                full: java.lang.String
                nullable: true
          constructors:
          - modifiers:
            - public
          staticMethods:
          - name: GetFaceIdForString
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: int
                full: int
          - name: GetObjectInfo
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: ObjectInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo
          - name: GetObjectInfoList
            modifiers:
            - public
            - static
            return:
              type:
                basic: ObjectInfo>
                full: java.util.ArrayList<zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo>
          - name: HasLoadErrors
            modifiers:
            - public
            - static
            return:
              type:
                basic: boolean
                full: boolean
          - name: InitScriptsPostTileDef
            modifiers:
            - public
            - static
            return:
              type:
                basic: void
                full: void
          - name: Reset
            modifiers:
            - public
            - static
            return:
              type:
                basic: void
                full: void
          - name: getObjectInfoFromSprite
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: ObjectInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$ObjectInfo
          javaType: class
          extends: Object
