version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.spriteconfig:
        SpriteConfigManager.FaceInfo:
          methods:
          - name: getFaceName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getHeight
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterTileInfo
            modifiers:
            - public
            return:
              type:
                basic: TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: getMasterX
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterY
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getMasterZ
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTileInfo
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: int
                full: int
            return:
              type:
                basic: TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: getTileInfoForSprite
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: TileInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$TileInfo
          - name: getWidth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getzLayers
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: isMasterSet
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isMultiSquare
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: verifyObject
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            - name: arg1
              type:
                basic: int
                full: int
            - name: arg2
              type:
                basic: int
                full: int
            - name: arg3
              type:
                basic: IsoObject
                full: zombie.iso.IsoObject
            return:
              type:
                basic: boolean
                full: boolean
          javaType: class
          extends: Object
