version: '1.1'
languages:
  java:
    packages:
      zombie.entity.components.spriteconfig:
        SpriteConfigManager$ObjectInfo:
          methods:
          - name: canRotate
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getFace
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: FaceInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$FaceInfo
          - name: getFace
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: FaceInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$FaceInfo
          - name: getFaceForSprite
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: FaceInfo
                full: zombie.entity.components.spriteconfig.SpriteConfigManager$FaceInfo
          - name: getIconTexture
            modifiers:
            - public
            return:
              type:
                basic: Texture
                full: zombie.core.textures.Texture
          - name: getMainSpriteNameUI
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getRecipe
            modifiers:
            - public
            return:
              type:
                basic: CraftRecipeComponentScript
                full: zombie.scripting.entity.components.crafting.CraftRecipeComponentScript
          - name: getRequiredSkillCount
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getScript
            modifiers:
            - public
            return:
              type:
                basic: SpriteConfigScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript
          - name: getTags
            modifiers:
            - public
            return:
              type:
                basic: List<String>
                full: java.util.List<java.lang.String>
          - name: getTime
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getVersion
            modifiers:
            - public
            return:
              type:
                basic: long
                full: long
          - name: isProp
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isSingleFace
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: needToBeLearn
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          javaType: class
          extends: Object
