version: '1.1'
languages:
  java:
    packages:
      javax.swing:
        Action:
          extends: java.lang.Object
          modifiers:
          - public
          - abstract
          staticFields:
            ACCELERATOR_KEY:
              name: ACCELERATOR_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            ACTION_COMMAND_KEY:
              name: ACTION_COMMAND_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            DEFAULT:
              name: DEFAULT
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            DISPLAYED_MNEMONIC_INDEX_KEY:
              name: DISPLAYED_MNEMONIC_INDEX_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            LARGE_ICON_KEY:
              name: LARGE_ICON_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            LONG_DESCRIPTION:
              name: LONG_DESCRIPTION
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            MNEMONIC_KEY:
              name: MNEMONIC_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            NAME:
              name: NAME
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            SELECTED_KEY:
              name: SELECTED_KEY
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            SHORT_DESCRIPTION:
              name: SHORT_DESCRIPTION
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
            SMALL_ICON:
              name: SMALL_ICON
              modifiers:
              - public
              - static
              type:
                basic: String
                full: java.lang.String
          methods:
          - name: accept
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
          - name: addPropertyChangeListener
            modifiers:
            - public
            - abstract
            parameters:
            - name: arg0
              type:
                basic: PropertyChangeListener
                full: java.beans.PropertyChangeListener
            return:
              type:
                basic: void
                full: void
          - name: getValue
            modifiers:
            - public
            - abstract
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: Object
                full: java.lang.Object
          - name: isEnabled
            modifiers:
            - public
            - abstract
            return:
              type:
                basic: boolean
                full: boolean
          - name: putValue
            modifiers:
            - public
            - abstract
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            - name: arg1
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: void
                full: void
          - name: removePropertyChangeListener
            modifiers:
            - public
            - abstract
            parameters:
            - name: arg0
              type:
                basic: PropertyChangeListener
                full: java.beans.PropertyChangeListener
            return:
              type:
                basic: void
                full: void
          - name: setEnabled
            modifiers:
            - public
            - abstract
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
