version: '1.1'
languages:
  java:
    packages:
      java.util:
        Stack:
          extends: java.util.Vector<E>
          modifiers:
          - public
          notes: "The Stack class represents a last-in-first-out\n (LIFO) stack of\
            \ objects. It extends class Vector with five\n operations that allow a\
            \ vector to be treated as a stack. The usual\n push and pop operations\
            \ are provided, as well as a\n method to peek at the top item on the stack,\
            \ a method to test\n for whether the stack is empty, and a method to search\n\
            \ the stack for an item and discover how far it is from the top.\n \n\
            \ When a stack is first created, it contains no items.\n\n A more complete\
            \ and consistent set of LIFO stack operations is\n provided by the Deque\
            \ interface and its implementations, which\n should be used in preference\
            \ to this class.  For example:\n    <code>\n   Deque<Integer> stack =\
            \ new ArrayDeque<Integer>();</code>"
          staticFields:
            serialVersionUID:
              name: serialVersionUID
              modifiers:
              - private
              - static
              type:
                basic: long
                full: long
          constructors:
          - modifiers:
            - public
            notes: Creates an empty Stack.
          methods:
          - name: empty
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
              notes: "true if and only if this stack contains\n          no items;\
                \ false otherwise."
            notes: Tests if this stack is empty.
          - name: peek
            modifiers:
            - public
            return:
              type:
                basic: E
                full: E
              notes: "the object at the top of this stack (the last item\n       \
                \   of the Vector object)."
            notes: "Looks at the object at the top of this stack without removing\
              \ it\n from the stack."
          - name: pop
            modifiers:
            - public
            return:
              type:
                basic: E
                full: E
              notes: "The object at the top of this stack (the last item\n       \
                \   of the Vector object)."
            notes: "Removes the object at the top of this stack and returns that\n\
              \ object as the value of this function."
          - name: push
            modifiers:
            - public
            parameters:
            - name: item
              type:
                basic: E
                full: E
              notes: the item to be pushed onto this stack.
            return:
              type:
                basic: E
                full: E
              notes: the item argument.
            notes: "Pushes an item onto the top of this stack. This has exactly\n\
              \ the same effect as:\n \n addElement(item)"
          - name: search
            modifiers:
            - public
            parameters:
            - name: o
              type:
                basic: Object
                full: java.lang.Object
              notes: the desired object.
            return:
              type:
                basic: int
                full: int
              notes: "the 1-based position from the top of the stack where\n     \
                \     the object is located; the return value -1\n          indicates\
                \ that the object is not on the stack."
            notes: "Returns the 1-based position where an object is on this stack.\n\
              \ If the object o occurs as an item in this stack, this\n method returns\
              \ the distance from the top of the stack of the\n occurrence nearest\
              \ the top of the stack; the topmost item on the\n stack is considered\
              \ to be at distance 1. The equals\n method is used to compare o to the\n\
              \ items in this stack."
