version: '1.1'
languages:
  java:
    packages:
      java.util:
        Stack:
          constructors:
          - modifiers:
            - public
          methods:
          - name: empty
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: peek
            modifiers:
            - public
            return:
              type:
                basic: E
                full: E
          - name: pop
            modifiers:
            - public
            return:
              type:
                basic: E
                full: E
          - name: push
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: E
                full: E
            return:
              type:
                basic: E
                full: E
          - name: search
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: int
                full: int
          javaType: class
          extends: Vector<E>
