version: '1.1'
languages:
  java:
    packages:
      zombie.core.physics:
        RagdollSettingsManager:
          staticFields:
            DefaultImpulse:
              name: DefaultImpulse
              modifiers:
              - public
              - static
              - final
              type:
                basic: float
                full: float
                nullable: true
            DefaultImpulseMax:
              name: DefaultImpulseMax
              modifiers:
              - public
              - static
              - final
              type:
                basic: float
                full: float
                nullable: true
            DefaultImpulseMin:
              name: DefaultImpulseMin
              modifiers:
              - public
              - static
              - final
              type:
                basic: float
                full: float
                nullable: true
            DefaultUpwardImpulse:
              name: DefaultUpwardImpulse
              modifiers:
              - public
              - static
              - final
              type:
                basic: float
                full: float
                nullable: true
            DefaultUpwardImpulseMax:
              name: DefaultUpwardImpulseMax
              modifiers:
              - public
              - static
              - final
              type:
                basic: float
                full: float
                nullable: true
            DefaultUpwardImpulseMin:
              name: DefaultUpwardImpulseMin
              modifiers:
              - public
              - static
              - final
              type:
                basic: float
                full: float
                nullable: true
            GlobalChanceID:
              name: GlobalChanceID
              modifiers:
              - public
              - static
              - final
              type:
                basic: int
                full: int
                nullable: true
          constructors:
          - modifiers:
            - public
          methods:
          - name: getChanceSetting
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: RagdollBodyPart
                full: zombie.core.physics.RagdollBodyPart
            return:
              type:
                basic: float
                full: float
          - name: getEnabledSetting
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: RagdollBodyPart
                full: zombie.core.physics.RagdollBodyPart
            return:
              type:
                basic: boolean
                full: boolean
          - name: getForceHitReactionLocation
            modifiers:
            - public
            return:
              type:
                basic: ForceHitReactionLocation
                full: zombie.core.physics.RagdollSettingsManager$ForceHitReactionLocation
          - name: getForceHitReactionLocation
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: ForceHitReactionLocation
                full: zombie.core.physics.RagdollSettingsManager$ForceHitReactionLocation
          - name: getForcedHitReactionLocationAsShotLocation
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getGlobalImpulseSetting
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getGlobalUpImpulseSetting
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getHitReactionLocationsCount
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getHitReactionSetting
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: HitReactionSetting
                full: zombie.core.physics.RagdollSettingsManager$HitReactionSetting
          - name: getHitReactionSettingsCount
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getImpulseSetting
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: RagdollBodyPart
                full: zombie.core.physics.RagdollBodyPart
            return:
              type:
                basic: float
                full: float
          - name: getSandboxHitReactionFrequency
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getSandboxHitReactionImpulseStrength
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getSandboxHitReactionUpImpulseStrength
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: getSetting
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: RagdollSetting
                full: zombie.core.physics.RagdollSettingsManager$RagdollSetting
          - name: getSettingsCount
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getUpImpulseSetting
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: RagdollBodyPart
                full: zombie.core.physics.RagdollBodyPart
            return:
              type:
                basic: float
                full: float
          - name: isForcedHitReaction
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: resetToDefaults
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: update
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: usePhysicHitReaction
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IsoZombie
                full: zombie.characters.IsoZombie
            return:
              type:
                basic: boolean
                full: boolean
          staticMethods:
          - name: getInstance
            modifiers:
            - public
            - static
            return:
              type:
                basic: RagdollSettingsManager
                full: zombie.core.physics.RagdollSettingsManager
          - name: setInstance
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: RagdollSettingsManager
                full: zombie.core.physics.RagdollSettingsManager
            return:
              type:
                basic: void
                full: void
          javaType: class
          extends: Object
