version: '1.1'
languages:
  java:
    packages:
      zombie.core.physics:
        RagdollSettingsManager.ForceHitReactionLocation:
          constructors:
          - modifiers:
            - public
          methods:
          - name: getAdminValue
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getID
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: init
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            - name: arg1
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: ForceHitReactionLocation
                full: zombie.core.physics.RagdollSettingsManager$ForceHitReactionLocation
          - name: isEnableAdmin
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: setAdminValue
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setEnableAdmin
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          javaType: class
          extends: Object
