version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript:
          methods:
          - name: OnScriptsLoaded
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ScriptLoadMode
                full: zombie.scripting.ScriptLoadMode
            return:
              type:
                basic: void
                full: void
          - name: PreReload
            modifiers:
            - public
            return:
              type:
                basic: void
                full: void
          - name: getAllTileNames
            modifiers:
            - public
            return:
              type:
                basic: ArrayList<String>
                full: java.util.ArrayList<java.lang.String>
          - name: getBonusHealth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getBreakSound
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getCornerSprite
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getDebugItem
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getDontNeedFrame
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getFace
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: FaceScript
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$FaceScript
          - name: getHealth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getIsThumpable
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getLightRadius
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLightsourceFuel
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getLightsourceItem
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getLightsourceTagItem
            modifiers:
            - public
            return:
              type:
                basic: ArrayList<String>
                full: java.util.ArrayList<java.lang.String>
          - name: getNeedToBeAgainstWall
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getNeedWindowFrame
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: getOnCreate
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getOnIsValid
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getPreviousStages
            modifiers:
            - public
            return:
              type:
                basic: ArrayList<String>
                full: java.util.ArrayList<java.lang.String>
          - name: getSkillBaseHealth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getVersion
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: IVersionHash
                full: zombie.world.scripts.IVersionHash
            return:
              type:
                basic: void
                full: void
          - name: isMultiTile
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isProp
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isSingleFace
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isValid
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isoMasterOnly
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          javaType: class
          extends: ComponentScript
