version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript$TileScript:
          constructors:
          - modifiers:
            - public
          methods:
          - name: getTileName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: isBlocksSquare
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: isEmptySpace
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          javaType: class
          extends: Object
