version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript$FaceScript:
          constructors:
          - modifiers:
            - public
          methods:
          - name: getFaceName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getLayer
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: ZLayer
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$ZLayer
          - name: getLightsourceOffsetX
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLightsourceOffsetY
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getLightsourceOffsetZ
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTotalHeight
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getTotalWidth
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getZLayers
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          javaType: class
          extends: Object
