version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.entity.components.spriteconfig:
        SpriteConfigScript.ZLayer:
          constructors:
          - modifiers:
            - public
          methods:
          - name: getHeight
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getRow
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: XRow
                full: zombie.scripting.entity.components.spriteconfig.SpriteConfigScript$XRow
          javaType: class
          extends: Object
