version: '1.1'
languages:
  java:
    packages:
      java.lang.module:
        Configuration:
          methods:
          - name: __toString__
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: findModule
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: Optional<ResolvedModule>
                full: java.util.Optional<java.lang.module.ResolvedModule>
          - name: modules
            modifiers:
            - public
            return:
              type:
                basic: Set<ResolvedModule>
                full: java.util.Set<java.lang.module.ResolvedModule>
          - name: parents
            modifiers:
            - public
            return:
              type:
                basic: List<Configuration>
                full: java.util.List<java.lang.module.Configuration>
          - name: resolve
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ModuleFinder
                full: java.lang.module.ModuleFinder
            - name: arg1
              type:
                basic: ModuleFinder
                full: java.lang.module.ModuleFinder
            - name: arg2
              type:
                basic: Collection<String>
                full: java.util.Collection<java.lang.String>
            return:
              type:
                basic: Configuration
                full: java.lang.module.Configuration
          - name: resolveAndBind
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ModuleFinder
                full: java.lang.module.ModuleFinder
            - name: arg1
              type:
                basic: ModuleFinder
                full: java.lang.module.ModuleFinder
            - name: arg2
              type:
                basic: Collection<String>
                full: java.util.Collection<java.lang.String>
            return:
              type:
                basic: Configuration
                full: java.lang.module.Configuration
          staticMethods:
          - name: empty
            modifiers:
            - public
            - static
            return:
              type:
                basic: Configuration
                full: java.lang.module.Configuration
          - name: resolve
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: ModuleFinder
                full: java.lang.module.ModuleFinder
            - name: arg1
              type:
                basic: List<Configuration>
                full: java.util.List<java.lang.module.Configuration>
            - name: arg2
              type:
                basic: ModuleFinder
                full: java.lang.module.ModuleFinder
            - name: arg3
              type:
                basic: Collection<String>
                full: java.util.Collection<java.lang.String>
            return:
              type:
                basic: Configuration
                full: java.lang.module.Configuration
          - name: resolveAndBind
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: ModuleFinder
                full: java.lang.module.ModuleFinder
            - name: arg1
              type:
                basic: List<Configuration>
                full: java.util.List<java.lang.module.Configuration>
            - name: arg2
              type:
                basic: ModuleFinder
                full: java.lang.module.ModuleFinder
            - name: arg3
              type:
                basic: Collection<String>
                full: java.util.Collection<java.lang.String>
            return:
              type:
                basic: Configuration
                full: java.lang.module.Configuration
          javaType: class
          extends: Object
