version: '1.1'
languages:
  java:
    packages:
      zombie.inventory.types:
        Clothing.ClothingPatch:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            biteDefense:
              name: biteDefense
              modifiers:
              - public
              type:
                basic: int
                full: int
            conditionGain:
              name: conditionGain
              modifiers:
              - public
              type:
                basic: int
                full: int
            fabricType:
              name: fabricType
              modifiers:
              - public
              type:
                basic: int
                full: int
            hasHole:
              name: hasHole
              modifiers:
              - public
              type:
                basic: boolean
                full: boolean
            scratchDefense:
              name: scratchDefense
              modifiers:
              - public
              type:
                basic: int
                full: int
            tailorLvl:
              name: tailorLvl
              modifiers:
              - public
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
          - modifiers:
            - public
            parameters:
            - name: tailorLvl
              type:
                basic: int
                full: int
            - name: fabricType
              type:
                basic: int
                full: int
            - name: hasHole
              type:
                basic: boolean
                full: boolean
          methods:
          - name: getBiteDefense
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getFabricType
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: getFabricTypeName
            modifiers:
            - public
            return:
              type:
                basic: String
                full: java.lang.String
          - name: getScratchDefense
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          - name: load
            modifiers:
            - public
            parameters:
            - name: input
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: WorldVersion
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: load_old
            modifiers:
            - public
            parameters:
            - name: input
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: WorldVersion
              type:
                basic: int
                full: int
            - name: net
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: save
            modifiers:
            - public
            parameters:
            - name: output
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: net
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: save_old
            modifiers:
            - public
            parameters:
            - name: output
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: net
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
