version: '1.1'
languages:
  java:
    packages:
      zombie.inventory.types:
        Key.HighlightDoor:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            doors:
              name: doors
              modifiers:
              - public
              type:
                basic: ArrayList
                full: java.util.ArrayList<zombie.iso.IsoObject>
            key:
              name: key
              modifiers:
              - public
              type:
                basic: Key
                full: zombie.inventory.types.Key
          constructors:
          - modifiers:
            - public
