version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemPickerJava.ItemPickerUpgradeWeapons:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            Upgrades:
              name: Upgrades
              modifiers:
              - public
              type:
                basic: ArrayList
                full: java.util.ArrayList<java.lang.String>
            name:
              name: name
              modifiers:
              - public
              type:
                basic: String
                full: java.lang.String
          constructors:
          - modifiers:
            - public
