version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemPickInfo:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            containerID:
              name: containerID
              modifiers:
              - private
              type:
                basic: int
                full: int
            exterior:
              name: exterior
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            isJunk:
              name: isJunk
              modifiers:
              - private
              type:
                basic: boolean
                full: boolean
            itemContainer:
              name: itemContainer
              modifiers:
              - private
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            resultValue:
              name: resultValue
              modifiers:
              - private
              type:
                basic: float
                full: float
            roomDist:
              name: roomDist
              modifiers:
              - private
              type:
                basic: ItemPickerJava.ItemPickerRoom
                full: zombie.inventory.ItemPickerJava$ItemPickerRoom
            roomID:
              name: roomID
              modifiers:
              - private
              type:
                basic: int
                full: int
            tileCount:
              name: tileCount
              modifiers:
              - private
              type:
                basic: int
                full: int
            tiles:
              name: tiles
              modifiers:
              - private
              type:
                basic: int
                full: int[]
            vehicleID:
              name: vehicleID
              modifiers:
              - private
              type:
                basic: int
                full: int
            worldAgeDays:
              name: worldAgeDays
              modifiers:
              - private
              type:
                basic: int
                full: int
            zoneCount:
              name: zoneCount
              modifiers:
              - private
              type:
                basic: int
                full: int
            zones:
              name: zones
              modifiers:
              - private
              type:
                basic: int
                full: int[]
          staticFields:
            instance:
              name: instance
              modifiers:
              - private
              - static
              type:
                basic: ItemPickInfo
                full: zombie.inventory.ItemPickInfo
          constructors:
          - modifiers:
            - private
          methods:
          - name: getResultValue
            modifiers:
            - public
            return:
              type:
                basic: float
                full: float
          - name: isJunk
            modifiers:
            - protected
            return:
              type:
                basic: boolean
                full: boolean
          - name: isMatch
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: SelectorBucket
                full: zombie.scripting.itemConfig.SelectorBucket
            return:
              type:
                basic: boolean
                full: boolean
          - name: isShop
            modifiers:
            - protected
            return:
              type:
                basic: boolean
                full: boolean
          - name: reset
            modifiers:
            - private
            return:
              type:
                basic: void
                full: void
          - name: setJunk
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: boolean
                full: boolean
            return:
              type:
                basic: void
                full: void
          - name: setResultValue
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: float
                full: float
            return:
              type:
                basic: void
                full: void
          - name: updateRoomDist
            modifiers:
            - protected
            parameters:
            - name: arg0
              type:
                basic: ItemPickerJava.ItemPickerRoom
                full: zombie.inventory.ItemPickerJava$ItemPickerRoom
            return:
              type:
                basic: void
                full: void
          staticMethods:
          - name: GetPickInfo
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            - name: arg1
              type:
                basic: ItemPickInfo.Caller
                full: zombie.inventory.ItemPickInfo$Caller
            return:
              type:
                basic: ItemPickInfo
                full: zombie.inventory.ItemPickInfo
          - name: getRoomDist
            modifiers:
            - private
            - static
            parameters:
            - name: arg0
              type:
                basic: IsoGridSquare
                full: zombie.iso.IsoGridSquare
            - name: arg1
              type:
                basic: ItemContainer
                full: zombie.inventory.ItemContainer
            return:
              type:
                basic: ItemPickerJava.ItemPickerRoom
                full: zombie.inventory.ItemPickerJava$ItemPickerRoom
