version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemType:
          extends: java.lang.Enum<zombie.inventory.ItemType>
          modifiers:
          - public
          - final
          fields:
            index:
              name: index
              modifiers:
              - private
              type:
                basic: int
                full: int
          staticFields:
            $VALUES:
              name: $VALUES
              modifiers:
              - private
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType[]
            AlarmClock:
              name: AlarmClock
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            AlarmClockClothing:
              name: AlarmClockClothing
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            Animal:
              name: Animal
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            Clothing:
              name: Clothing
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            Drainable:
              name: Drainable
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            Food:
              name: Food
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            Key:
              name: Key
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            KeyRing:
              name: KeyRing
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            Literature:
              name: Literature
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            Moveable:
              name: Moveable
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            None:
              name: None
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
            Weapon:
              name: Weapon
              modifiers:
              - public
              - static
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
          constructors:
          - modifiers:
            - private
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
          methods:
          - name: index
            modifiers:
            - public
            return:
              type:
                basic: int
                full: int
          staticMethods:
          - name: $values
            modifiers:
            - private
            - static
            return:
              type:
                basic: ItemType
                full: zombie.inventory.ItemType[]
          - name: fromIndex
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: int
                full: int
            return:
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
          - name: valueOf
            modifiers:
            - public
            - static
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: ItemType
                full: zombie.inventory.ItemType
          - name: values
            modifiers:
            - public
            - static
            return:
              type:
                basic: ItemType
                full: zombie.inventory.ItemType[]
