version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemContainer.InventoryItemList:
          extends: java.util.ArrayList<zombie.inventory.InventoryItem>
          modifiers:
          - package
          - final
          constructors:
          - modifiers:
            - private
          methods:
          - name: equals
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Object
                full: java.lang.Object
            return:
              type:
                basic: boolean
                full: boolean
