version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemFilter:
          extends: java.lang.Object
          modifiers:
          - public
          fields:
            filterScript:
              name: filterScript
              modifiers:
              - private
              type:
                basic: ItemFilterScript
                full: zombie.scripting.objects.ItemFilterScript
          constructors:
          - modifiers:
            - public
          methods:
          - name: allows
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: boolean
                full: boolean
          - name: allows
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: InventoryItem
                full: zombie.inventory.InventoryItem
            return:
              type:
                basic: boolean
                full: boolean
          - name: allows
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: Item
                full: zombie.scripting.objects.Item
            return:
              type:
                basic: boolean
                full: boolean
          - name: getFilterScript
            modifiers:
            - public
            return:
              type:
                basic: ItemFilterScript
                full: zombie.scripting.objects.ItemFilterScript
          - name: isActive
            modifiers:
            - public
            return:
              type:
                basic: boolean
                full: boolean
          - name: load
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            - name: arg1
              type:
                basic: int
                full: int
            return:
              type:
                basic: void
                full: void
          - name: save
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: ByteBuffer
                full: java.nio.ByteBuffer
            return:
              type:
                basic: void
                full: void
          - name: setFilterScript
            modifiers:
            - public
            parameters:
            - name: arg0
              type:
                basic: String
                full: java.lang.String
            return:
              type:
                basic: void
                full: void
