version: '1.1'
languages:
  java:
    packages:
      zombie.inventory:
        ItemPickerJava.ProceduralItem:
          extends: java.lang.Object
          modifiers:
          - public
          - final
          fields:
            forceForItems:
              name: forceForItems
              modifiers:
              - public
              type:
                basic: List
                full: java.util.List<java.lang.String>
            forceForRooms:
              name: forceForRooms
              modifiers:
              - public
              type:
                basic: List
                full: java.util.List<java.lang.String>
            forceForTiles:
              name: forceForTiles
              modifiers:
              - public
              type:
                basic: List
                full: java.util.List<java.lang.String>
            forceForZones:
              name: forceForZones
              modifiers:
              - public
              type:
                basic: List
                full: java.util.List<java.lang.String>
            max:
              name: max
              modifiers:
              - public
              type:
                basic: int
                full: int
            min:
              name: min
              modifiers:
              - public
              type:
                basic: int
                full: int
            name:
              name: name
              modifiers:
              - public
              type:
                basic: String
                full: java.lang.String
            weightChance:
              name: weightChance
              modifiers:
              - public
              type:
                basic: int
                full: int
          constructors:
          - modifiers:
            - public
