version: '1.1'
languages:
  java:
    packages:
      zombie.scripting.objects:
        Recipe:
          modifiers:
          - public
          fields:
            AllowDestroyedItem:
              name: AllowDestroyedItem
              modifiers:
              - public
              type:
                basic: boolean
            AllowFrozenItem:
              name: AllowFrozenItem
              modifiers:
              - public
              type:
                basic: boolean
            InSameInventory:
              name: InSameInventory
              modifiers:
              - public
              type:
                basic: boolean
            LuaCreate:
              name: LuaCreate
              modifiers:
              - public
              type:
                basic: String
            LuaGiveXP:
              name: LuaGiveXP
              modifiers:
              - public
              type:
                basic: String
            LuaGrab:
              name: LuaGrab
              modifiers:
              - public
              type:
                basic: String
            LuaTest:
              name: LuaTest
              modifiers:
              - public
              type:
                basic: String
            Result:
              name: Result
              modifiers:
              - public
              type:
                basic: Result
            Sound:
              name: Sound
              modifiers:
              - public
              type:
                basic: String
            Source:
              name: Source
              modifiers:
              - public
              - final
              type:
                basic: ArrayList
            TimeToMake:
              name: TimeToMake
              modifiers:
              - public
              type:
                basic: float
            hidden:
              name: hidden
              modifiers:
              - public
              type:
                basic: boolean
            name:
              name: name
              modifiers:
              - public
              type:
                basic: String
            skillRequired:
              name: skillRequired
              modifiers:
              - public
              type:
                basic: ArrayList
          constructors:
          - modifiers:
            - public
          methods:
          - name: DoResult
            modifiers:
            - public
            parameters:
            - name: type
              type:
                basic: String
            return:
              type:
                basic: void
          - name: DoSource
            modifiers:
            - public
            parameters:
            - name: type
              type:
                basic: String
            return:
              type:
                basic: void
          - name: FindIndexOf
            modifiers:
            - public
            parameters:
            - name: a
              type:
                basic: InventoryItem
            return:
              type:
                basic: int
          - name: Load
            modifiers:
            - public
            parameters:
            - name: name
              type:
                basic: String
            - name: strArray
              type:
                basic: String[]
            return:
              type:
                basic: void
          - name: addRequiredSkill
            modifiers:
            - public
            parameters:
            - name: perk
              type:
                basic: Perk
            - name: level
              type:
                basic: int
            return:
              type:
                basic: void
          - name: clearRequiredSkills
            modifiers:
            - public
            return:
              type:
                basic: void
          - name: findSource
            modifiers:
            - public
            parameters:
            - name: sourceFullType
              type:
                basic: String
            return:
              type:
                basic: Source
          - name: getAnimNode
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getCanPerform
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getCategory
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getFullType
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getHeat
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getLuaCreate
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getLuaGiveXP
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getLuaGrab
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getLuaTest
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getName
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getNearItem
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getNumberOfNeededItem
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getOriginalname
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getProp1
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getProp2
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getRequiredSkill
            modifiers:
            - public
            parameters:
            - name: index
              type:
                basic: int
            return:
              type:
                basic: RequiredSkill
          - name: getRequiredSkillCount
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: getRequiredSkills
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
          - name: getResult
            modifiers:
            - public
            return:
              type:
                basic: Result
          - name: getSound
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getSource
            modifiers:
            - public
            return:
              type:
                basic: ArrayList
          - name: getTimeToMake
            modifiers:
            - public
            return:
              type:
                basic: float
          - name: getTooltip
            modifiers:
            - public
            return:
              type:
                basic: String
          - name: getWaterAmountNeeded
            modifiers:
            - public
            return:
              type:
                basic: int
          - name: isAllowDestroyedItem
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isAllowFrozenItem
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isCanBeDoneFromFloor
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isDestroy
            modifiers:
            - public
            parameters:
            - name: sourceFullType
              type:
                basic: String
            return:
              type:
                basic: boolean
          - name: isHidden
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isKeep
            modifiers:
            - public
            parameters:
            - name: sourceFullType
              type:
                basic: String
            return:
              type:
                basic: boolean
          - name: isRemoveResultItem
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isStopOnRun
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: isStopOnWalk
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: needToBeLearn
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: noBrokenItems
            modifiers:
            - public
            return:
              type:
                basic: boolean
          - name: setAllowDestroyedItem
            modifiers:
            - public
            parameters:
            - name: allow
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setAllowFrozenItem
            modifiers:
            - public
            parameters:
            - name: allow
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setAnimNode
            modifiers:
            - public
            parameters:
            - name: animNode
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setCanBeDoneFromFloor
            modifiers:
            - public
            parameters:
            - name: canBeDoneFromFloor
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setCanPerform
            modifiers:
            - public
            parameters:
            - name: functionName
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setCategory
            modifiers:
            - public
            parameters:
            - name: category
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setIsHidden
            modifiers:
            - public
            parameters:
            - name: hide
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setLuaCreate
            modifiers:
            - public
            parameters:
            - name: functionName
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setLuaGiveXP
            modifiers:
            - public
            parameters:
            - name: functionName
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setLuaGrab
            modifiers:
            - public
            parameters:
            - name: functionName
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setLuaTest
            modifiers:
            - public
            parameters:
            - name: functionName
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setNearItem
            modifiers:
            - public
            parameters:
            - name: nearItem
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setNeedToBeLearn
            modifiers:
            - public
            parameters:
            - name: needToBeLearn
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setOriginalname
            modifiers:
            - public
            parameters:
            - name: originalname
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setProp1
            modifiers:
            - public
            parameters:
            - name: prop1
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setProp2
            modifiers:
            - public
            parameters:
            - name: prop2
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setRemoveResultItem
            modifiers:
            - public
            parameters:
            - name: removeResultItem
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setSound
            modifiers:
            - public
            parameters:
            - name: sound
              type:
                basic: String
            return:
              type:
                basic: void
          - name: setStopOnRun
            modifiers:
            - public
            parameters:
            - name: stop
              type:
                basic: boolean
            return:
              type:
                basic: void
          - name: setStopOnWalk
            modifiers:
            - public
            parameters:
            - name: stop
              type:
                basic: boolean
            return:
              type:
                basic: void
          javaType: class
          extends: BaseScriptObject
